organization = "revanced"
patches = { repository = "revanced-patches", asset-regex = "jar$", signature-asset-regex = "asc$", public-key-file = "key.asc" }
integrations = { repository = "revanced-integrations", asset-regex = "apk$", signature-asset-regex = "asc$", public-key-file = "key.asc" }
contributors-repositories = [
    "revanced-patcher",
    "revanced-patches",
    "revanced-integrations",
    "revanced-website",
    "revanced-cli",
    "revanced-manager",
]
api-version = 1
host = "*.revanced.app"