FROM azul/zulu-openjdk:latest

ARG CONFIG_FILE_PATH

ARG DB_URL
ARG DB_USER
ARG DB_PASSWORD

ARG JWT_SECRET
ARG JWT_ISSUER
ARG JWT_VALIDITY_IN_MIN

ARG BASIC_USERNAME
ARG BASIC_PASSWORD

ENV CONFIG_FILE_PATH $CONFIG_FILE_PATH

ENV DB_URL $DB_URL
ENV DB_USER $DB_USER
ENV DB_PASSWORD $DB_PASSWORD

ENV JWT_SECRET $JWT_SECRET
ENV JWT_ISSUER $JWT_ISSUER
ENV JWT_VALIDITY_IN_MIN $JWT_VALIDITY_IN_MIN

ENV BASIC_USERNAME $BASIC_USERNAME
ENV BASIC_PASSWORD $BASIC_PASSWORD

COPY build/libs/revanced-api-*.jar revanced-api.jar

CMD java -jar revanced-api.jar start