name = "revanced-api"
main = "src/index.ts"
compatibility_date = "2025-02-01"

[[rules]]
type = "Text"
globs = ["**/*.txt"]

[[d1_databases]]
binding = "DB"
database_name = "revanced-api"
database_id = "<to-be-filled>"
migrations_dir = "drizzle/migrations"
