// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl:
        | 'https://api.revanced.app'
        | `${string}://{customServer}`
        | (string & {});
};

export type Release = {
    version: string;
    created_at: string;
    description: string;
    download_url: string;
    signature_download_url?: string;
};

export type Version = {
    version: string;
};

export type ReleaseSimple = {
    version: string;
    created_at: string;
    description: string;
};

export type PublicKey = {
    /**
     * The PGP public key for verifying patches assets.
     */
    patches_public_key: string;
};

export type Announcement = {
    id: number;
    author: string;
    title: string;
    content: string;
    tags: Array<string>;
    created_at: string;
    archived_at: string;
    level: number;
};

export type LatestAnnouncementsByTag = Array<LatestAnnouncementEntry>;

export type LatestAnnouncementEntry = {
    tag: string;
    announcement: Announcement;
};

export type LatestAnnouncementIdsByTag = Array<LatestAnnouncementIdEntry>;

export type LatestAnnouncementIdEntry = {
    tag: string;
    id: number;
};

export type CreateAnnouncement = {
    author?: string;
    title: string;
    content?: string;
    tags: Array<string>;
    /**
     * UTC timestamp. Defaults to current time if omitted.
     */
    created_at?: string;
    /**
     * UTC timestamp.
     */
    archived_at?: string;
    level?: number;
};

export type UpdateAnnouncement = {
    author?: string;
    title: string;
    content?: string;
    tags: Array<string>;
    /**
     * UTC timestamp.
     */
    created_at?: string;
    /**
     * UTC timestamp.
     */
    archived_at?: string;
    level?: number;
};

export type Contributable = {
    name: string;
    url: string;
    contributors: Array<{
        name: string;
        avatar_url: string;
        url: string;
        contributions: number;
    }>;
};

export type TeamMember = {
    name: string;
    avatar_url: string;
    url: string;
    bio: string;
    gpg_key: {
        id: string;
        url: string;
    };
};

export type About = {
    name: string;
    about: string;
    keys: string;
    branding?: {
        logo: string;
    };
    status: string;
    contact?: {
        email: string;
    };
    socials?: Array<{
        name: string;
        url: string;
        preferred?: boolean;
    }>;
    donations?: {
        wallets?: Array<{
            network: string;
            currency_code: string;
            address: string;
            preferred?: boolean;
        }>;
        links?: Array<{
            name: string;
            url: string;
            preferred?: boolean;
        }>;
    };
};

export type GetV5PatchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/patches';
};

export type GetV5PatchesErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5PatchesError = GetV5PatchesErrors[keyof GetV5PatchesErrors];

export type GetV5PatchesResponses = {
    /**
     * The current patches release.
     */
    200: Release;
};

export type GetV5PatchesResponse =
    GetV5PatchesResponses[keyof GetV5PatchesResponses];

export type GetV5PatchesPrereleaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/patches/prerelease';
};

export type GetV5PatchesPrereleaseErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5PatchesPrereleaseError =
    GetV5PatchesPrereleaseErrors[keyof GetV5PatchesPrereleaseErrors];

export type GetV5PatchesPrereleaseResponses = {
    /**
     * The current patches prerelease.
     */
    200: Release;
};

export type GetV5PatchesPrereleaseResponse =
    GetV5PatchesPrereleaseResponses[keyof GetV5PatchesPrereleaseResponses];

export type GetV5PatchesVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/patches/version';
};

export type GetV5PatchesVersionErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5PatchesVersionError =
    GetV5PatchesVersionErrors[keyof GetV5PatchesVersionErrors];

export type GetV5PatchesVersionResponses = {
    /**
     * The current patches release version.
     */
    200: Version;
};

export type GetV5PatchesVersionResponse =
    GetV5PatchesVersionResponses[keyof GetV5PatchesVersionResponses];

export type GetV5PatchesVersionPrereleaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/patches/version/prerelease';
};

export type GetV5PatchesVersionPrereleaseErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5PatchesVersionPrereleaseError =
    GetV5PatchesVersionPrereleaseErrors[keyof GetV5PatchesVersionPrereleaseErrors];

export type GetV5PatchesVersionPrereleaseResponses = {
    /**
     * The current patches prerelease version.
     */
    200: Version;
};

export type GetV5PatchesVersionPrereleaseResponse =
    GetV5PatchesVersionPrereleaseResponses[keyof GetV5PatchesVersionPrereleaseResponses];

export type GetV5PatchesHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/patches/history';
};

export type GetV5PatchesHistoryErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5PatchesHistoryError =
    GetV5PatchesHistoryErrors[keyof GetV5PatchesHistoryErrors];

export type GetV5PatchesHistoryResponses = {
    /**
     * The patches release history.
     */
    200: Array<ReleaseSimple>;
};

export type GetV5PatchesHistoryResponse =
    GetV5PatchesHistoryResponses[keyof GetV5PatchesHistoryResponses];

export type GetV5PatchesHistoryPrereleaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/patches/history/prerelease';
};

export type GetV5PatchesHistoryPrereleaseErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5PatchesHistoryPrereleaseError =
    GetV5PatchesHistoryPrereleaseErrors[keyof GetV5PatchesHistoryPrereleaseErrors];

export type GetV5PatchesHistoryPrereleaseResponses = {
    /**
     * The patches prerelease history.
     */
    200: Array<ReleaseSimple>;
};

export type GetV5PatchesHistoryPrereleaseResponse =
    GetV5PatchesHistoryPrereleaseResponses[keyof GetV5PatchesHistoryPrereleaseResponses];

export type GetV5PatchesKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/patches/keys';
};

export type GetV5PatchesKeysResponses = {
    /**
     * The public keys.
     */
    200: PublicKey;
};

export type GetV5PatchesKeysResponse =
    GetV5PatchesKeysResponses[keyof GetV5PatchesKeysResponses];

export type GetV5ManagerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/manager';
};

export type GetV5ManagerErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5ManagerError = GetV5ManagerErrors[keyof GetV5ManagerErrors];

export type GetV5ManagerResponses = {
    /**
     * The latest manager release.
     */
    200: Release;
};

export type GetV5ManagerResponse =
    GetV5ManagerResponses[keyof GetV5ManagerResponses];

export type GetV5ManagerPrereleaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/manager/prerelease';
};

export type GetV5ManagerPrereleaseErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5ManagerPrereleaseError =
    GetV5ManagerPrereleaseErrors[keyof GetV5ManagerPrereleaseErrors];

export type GetV5ManagerPrereleaseResponses = {
    /**
     * The latest manager prerelease.
     */
    200: Release;
};

export type GetV5ManagerPrereleaseResponse =
    GetV5ManagerPrereleaseResponses[keyof GetV5ManagerPrereleaseResponses];

export type GetV5ManagerVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/manager/version';
};

export type GetV5ManagerVersionErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5ManagerVersionError =
    GetV5ManagerVersionErrors[keyof GetV5ManagerVersionErrors];

export type GetV5ManagerVersionResponses = {
    /**
     * The current manager release version.
     */
    200: Version;
};

export type GetV5ManagerVersionResponse =
    GetV5ManagerVersionResponses[keyof GetV5ManagerVersionResponses];

export type GetV5ManagerVersionPrereleaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/manager/version/prerelease';
};

export type GetV5ManagerVersionPrereleaseErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5ManagerVersionPrereleaseError =
    GetV5ManagerVersionPrereleaseErrors[keyof GetV5ManagerVersionPrereleaseErrors];

export type GetV5ManagerVersionPrereleaseResponses = {
    /**
     * The current manager prerelease version.
     */
    200: Version;
};

export type GetV5ManagerVersionPrereleaseResponse =
    GetV5ManagerVersionPrereleaseResponses[keyof GetV5ManagerVersionPrereleaseResponses];

export type GetV5ManagerHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/manager/history';
};

export type GetV5ManagerHistoryErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5ManagerHistoryError =
    GetV5ManagerHistoryErrors[keyof GetV5ManagerHistoryErrors];

export type GetV5ManagerHistoryResponses = {
    /**
     * The manager release history.
     */
    200: Array<ReleaseSimple>;
};

export type GetV5ManagerHistoryResponse =
    GetV5ManagerHistoryResponses[keyof GetV5ManagerHistoryResponses];

export type GetV5ManagerHistoryPrereleaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/manager/history/prerelease';
};

export type GetV5ManagerHistoryPrereleaseErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5ManagerHistoryPrereleaseError =
    GetV5ManagerHistoryPrereleaseErrors[keyof GetV5ManagerHistoryPrereleaseErrors];

export type GetV5ManagerHistoryPrereleaseResponses = {
    /**
     * The manager prerelease history.
     */
    200: Array<ReleaseSimple>;
};

export type GetV5ManagerHistoryPrereleaseResponse =
    GetV5ManagerHistoryPrereleaseResponses[keyof GetV5ManagerHistoryPrereleaseResponses];

export type GetV5ManagerDownloadersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/manager/downloaders';
};

export type GetV5ManagerDownloadersErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5ManagerDownloadersError =
    GetV5ManagerDownloadersErrors[keyof GetV5ManagerDownloadersErrors];

export type GetV5ManagerDownloadersResponses = {
    /**
     * The latest manager downloaders release.
     */
    200: Release;
};

export type GetV5ManagerDownloadersResponse =
    GetV5ManagerDownloadersResponses[keyof GetV5ManagerDownloadersResponses];

export type GetV5ManagerDownloadersPrereleaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/manager/downloaders/prerelease';
};

export type GetV5ManagerDownloadersPrereleaseErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5ManagerDownloadersPrereleaseError =
    GetV5ManagerDownloadersPrereleaseErrors[keyof GetV5ManagerDownloadersPrereleaseErrors];

export type GetV5ManagerDownloadersPrereleaseResponses = {
    /**
     * The latest manager downloaders prerelease.
     */
    200: Release;
};

export type GetV5ManagerDownloadersPrereleaseResponse =
    GetV5ManagerDownloadersPrereleaseResponses[keyof GetV5ManagerDownloadersPrereleaseResponses];

export type GetV5ManagerDownloadersVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/manager/downloaders/version';
};

export type GetV5ManagerDownloadersVersionErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5ManagerDownloadersVersionError =
    GetV5ManagerDownloadersVersionErrors[keyof GetV5ManagerDownloadersVersionErrors];

export type GetV5ManagerDownloadersVersionResponses = {
    /**
     * The current manager downloaders release version.
     */
    200: Version;
};

export type GetV5ManagerDownloadersVersionResponse =
    GetV5ManagerDownloadersVersionResponses[keyof GetV5ManagerDownloadersVersionResponses];

export type GetV5ManagerDownloadersVersionPrereleaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/manager/downloaders/version/prerelease';
};

export type GetV5ManagerDownloadersVersionPrereleaseErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5ManagerDownloadersVersionPrereleaseError =
    GetV5ManagerDownloadersVersionPrereleaseErrors[keyof GetV5ManagerDownloadersVersionPrereleaseErrors];

export type GetV5ManagerDownloadersVersionPrereleaseResponses = {
    /**
     * The current manager downloaders prerelease version.
     */
    200: Version;
};

export type GetV5ManagerDownloadersVersionPrereleaseResponse =
    GetV5ManagerDownloadersVersionPrereleaseResponses[keyof GetV5ManagerDownloadersVersionPrereleaseResponses];

export type GetV5AnnouncementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/announcements';
};

export type GetV5AnnouncementsResponses = {
    /**
     * All announcements.
     */
    200: Array<Announcement>;
};

export type GetV5AnnouncementsResponse =
    GetV5AnnouncementsResponses[keyof GetV5AnnouncementsResponses];

export type PostV5AnnouncementsData = {
    body?: CreateAnnouncement;
    path?: never;
    query?: never;
    url: '/v5/announcements';
};

export type PostV5AnnouncementsErrors = {
    /**
     * Unauthorized.
     */
    401: {
        error: string;
    };
    /**
     * Forbidden.
     */
    403: {
        error: string;
    };
};

export type PostV5AnnouncementsError =
    PostV5AnnouncementsErrors[keyof PostV5AnnouncementsErrors];

export type PostV5AnnouncementsResponses = {
    /**
     * The created announcement.
     */
    201: Announcement;
};

export type PostV5AnnouncementsResponse =
    PostV5AnnouncementsResponses[keyof PostV5AnnouncementsResponses];

export type GetV5AnnouncementsLatestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/announcements/latest';
};

export type GetV5AnnouncementsLatestResponses = {
    /**
     * The newest announcement for each tag.
     */
    200: LatestAnnouncementsByTag;
};

export type GetV5AnnouncementsLatestResponse =
    GetV5AnnouncementsLatestResponses[keyof GetV5AnnouncementsLatestResponses];

export type GetV5AnnouncementsLatestIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/announcements/latest/id';
};

export type GetV5AnnouncementsLatestIdResponses = {
    /**
     * The newest announcement ID for each tag.
     */
    200: LatestAnnouncementIdsByTag;
};

export type GetV5AnnouncementsLatestIdResponse =
    GetV5AnnouncementsLatestIdResponses[keyof GetV5AnnouncementsLatestIdResponses];

export type DeleteV5AnnouncementsByIdData = {
    body?: never;
    path: {
        /**
         * Announcement ID.
         */
        id: number;
    };
    query?: never;
    url: '/v5/announcements/{id}';
};

export type DeleteV5AnnouncementsByIdErrors = {
    /**
     * Unauthorized.
     */
    401: {
        error: string;
    };
    /**
     * Forbidden.
     */
    403: {
        error: string;
    };
    /**
     * Announcement not found.
     */
    404: {
        error: string;
    };
};

export type DeleteV5AnnouncementsByIdError =
    DeleteV5AnnouncementsByIdErrors[keyof DeleteV5AnnouncementsByIdErrors];

export type DeleteV5AnnouncementsByIdResponses = {
    /**
     * Announcement deleted.
     */
    204: void;
};

export type DeleteV5AnnouncementsByIdResponse =
    DeleteV5AnnouncementsByIdResponses[keyof DeleteV5AnnouncementsByIdResponses];

export type PatchV5AnnouncementsByIdData = {
    body?: UpdateAnnouncement;
    path: {
        /**
         * Announcement ID.
         */
        id: number;
    };
    query?: never;
    url: '/v5/announcements/{id}';
};

export type PatchV5AnnouncementsByIdErrors = {
    /**
     * Unauthorized.
     */
    401: {
        error: string;
    };
    /**
     * Forbidden.
     */
    403: {
        error: string;
    };
    /**
     * Announcement not found.
     */
    404: {
        error: string;
    };
};

export type PatchV5AnnouncementsByIdError =
    PatchV5AnnouncementsByIdErrors[keyof PatchV5AnnouncementsByIdErrors];

export type PatchV5AnnouncementsByIdResponses = {
    /**
     * The updated announcement.
     */
    200: Announcement;
};

export type PatchV5AnnouncementsByIdResponse =
    PatchV5AnnouncementsByIdResponses[keyof PatchV5AnnouncementsByIdResponses];

export type GetV5ContributorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/contributors';
};

export type GetV5ContributorsErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5ContributorsError =
    GetV5ContributorsErrors[keyof GetV5ContributorsErrors];

export type GetV5ContributorsResponses = {
    /**
     * The list of contributors.
     */
    200: Array<Contributable>;
};

export type GetV5ContributorsResponse =
    GetV5ContributorsResponses[keyof GetV5ContributorsResponses];

export type GetV5TeamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/team';
};

export type GetV5TeamErrors = {
    /**
     * GitHub API error.
     */
    500: {
        error: string;
    };
};

export type GetV5TeamError = GetV5TeamErrors[keyof GetV5TeamErrors];

export type GetV5TeamResponses = {
    /**
     * The list of team members.
     */
    200: Array<TeamMember>;
};

export type GetV5TeamResponse = GetV5TeamResponses[keyof GetV5TeamResponses];

export type GetV5AboutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v5/about';
};

export type GetV5AboutResponses = {
    /**
     * Information about the API.
     */
    200: About;
};

export type GetV5AboutResponse = GetV5AboutResponses[keyof GetV5AboutResponses];
