name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bunx semantic-release

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: bunx db:migration:apply --remote
          command: deploy
          secrets: |
            API_TOKEN
            GITHUB_TOKEN
            ORGANIZATION
            PATCHES_REPO
            PATCHES_ASSET_REGEX
            PATCHES_SIGNATURE_ASSET_REGEX
            PATCHES_PUBLIC_KEY_FILE
            MANAGER_REPO
            MANAGER_ASSET_REGEX
            MANAGER_DOWNLOADERS_REPO
            MANAGER_DOWNLOADERS_ASSET_REGEX
            CONTRIBUTORS_REPOS
            API_VERSION
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.READ_REPOSITORIES_GITHUB_TOKEN }}
          ORGANIZATION: ${{ env.ORGANIZATION }}
          PATCHES_REPO: ${{ env.PATCHES_REPO }}
          PATCHES_ASSET_REGEX: ${{ env.PATCHES_ASSET_REGEX }}
          PATCHES_SIGNATURE_ASSET_REGEX: ${{ env.PATCHES_SIGNATURE_ASSET_REGEX }}
          PATCHES_PUBLIC_KEY_FILE: ${{ env.PATCHES_PUBLIC_KEY_FILE }}
          MANAGER_REPO: ${{ env.MANAGER_REPO }}
          MANAGER_ASSET_REGEX: ${{ env.MANAGER_ASSET_REGEX }}
          MANAGER_DOWNLOADERS_REPO: ${{ env.MANAGER_DOWNLOADERS_REPO }}
          MANAGER_DOWNLOADERS_ASSET_REGEX: ${{ env.MANAGER_DOWNLOADERS_ASSET_REGEX }}
          CONTRIBUTORS_REPOS: ${{ env.CONTRIBUTORS_REPOS }}
          API_VERSION: ${{ env.API_VERSION }}
