name: "Qodana | Code Quality Scan"

on:
  push:
    branches: [dev, main]
  pull_request:
    types: [opened, reopened, edited, synchronize]
  workflow_dispatch:

env:
  default_branch: dev

jobs:
  qodana:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2023.1.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      - name: "Upload Qodana Report"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
