name: "Qodana | Code Quality Scan"

on:
  push:
    branches: [dev, main]
  pull_request:
    types: [opened, reopened, edited, synchronize]
  workflow_dispatch:

env:
  default_branch: dev

jobs:
  qodana:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ];
          then pip install -r requirements.txt;
          fi

      - name: Install testing tools
        run: pip install mypy pydantic

      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2023.1.5
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: --baseline,qodana.sarif.json

      - name: "Upload Qodana Report"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
